spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: v1
          uri: http://localhost:8081
          predicates:
            - Path=/v1/**
          filters:
            - name: AddRequestHeader
              args:
                name: x-request-id
                value: "#{request.getHeader('x-request-id') ?: T(java.util.UUID).randomUUID().toString()}"
        - id: v2
          uri: http://localhost:8082
          predicates:
            - Path=/v2/**
          filters:
            - name: AddRequestHeader
              args:
                name: x-request-id
                value: "#{request.getHeader('x-request-id') ?: T(java.util.UUID).randomUUID().toString()}"

server:
  port: 8080

